classDiagram

class User {
    <<abstract>>
    id : String
    firstName : String
    lastName : String
    email : String
    password : String
    phone : String
    login()
    logout()
}

class Owner {
    siret : String
    registrationDate : Date
    validateReservation(r : Reservation)
    verifyCNI(cniUrl : String)
}

class Tenant {
    cin : String
    birthDate : Date
    searchField()
    reserve(c : TimeSlot, payload : ReservationPayload)
    cancelReservation(r : Reservation)
}

class Employee {
    position : String
    hireDate : Date
    verifyClientArrival(r : Reservation)
    viewSchedule()
}

User <|-- Owner
User <|-- Tenant
User <|-- Employee


class Field {
    id : String
    name : String
    description : String
    address : String
    pricePerHour : Float
    getAvailableTimeSlots()
}

class TimeSlot {
    id : String
    date : Date
    startTime : Time
    endTime : Time
    status : TimeSlotStatus
}

class TimeSlotStatus {
    AVAILABLE
    RESERVED
    UNAVAILABLE
}

Field "1" *-- "*" TimeSlot


class Reservation {
    id : String
    firstName : String
    lastName : String
    email : String
    phone : String
    requestDate : DateTime
    price : Float
    cniUrl : String
    status : ReservationStatus
    confirm()
    cancel()
}

class ReservationStatus {
    PENDING
    APPROVED
    REJECTED
    CANCELED
}

Tenant "1" --> "*" Reservation
Reservation "1" --> "1" TimeSlot
Employee "1" --> "*" Reservation


class Role {
    name : String
    guard_name : String
}

class Permission {
    name : String
    guard_name : String
}

User "*" -- "*" Role
Role "*" -- "*" Permission
User "*" -- "*" Permission


Owner "1" --> "*" Field